title: abnt-latex

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-date-localization

date_locale: pt

description: O abnt-latex Ã© um conjunto de recursos para facilitar a escrita de documentos escritos em LaTeX seguindo as normas da ABNT
logo: assets/logo.svg

exclude:
  - README.md